#
# Created by mandriy on 5/11/15.
#

executable_name ?= client
headers = ../socket/TCPSocket.h ../connection/connection.h
source_files = ../socket/TCPSocket.cpp
main_file = client.cpp
run_args = -l 25

include ../makefile