#
# Created by mandriy on 5/11/15.
#

executable_name ?= client
headers = ../socket/TCPSocket.h ../connection/connection.h
source_files = client.cpp ../socket/TCPSocket.cpp
flags += -lboost_program_options
run_args = -l 25

include ../makefile